### ISSUE TITLE
REQ: Ignore a Branch for Naming Conventions.

### ISSUE THREAD

**Issue by bbakermmc** [kerwinc/VSTSTasks#2]
We get code from a 3rd party which is what our solution is based on.  We keep this in a "base" branch so we always have a fresh copy of the their code w/out modifications.  It would be nice to "ignore" this branch in the "naming" conventions w/out having to turn the entire option off.

We maintain this branch outside of the gitflow scope.

**Comment by kerwinc** [comment]
Good suggestion. Do you think it would be good to ignore any branches under a path i.e. ignore: prototype/*, archive/*, external/* etc.. This would be configurable of course.

**Comment by bbakermmc** [comment]
Sure, sounds fine to me.

**Comment by kerwinc** [comment]
Hey bud. Finally got to add this. Switch to version 1 of the task and it's under **Advanced**. If you still using the build task, give it a go and let me know if it works for you.
